---
- hosts: host
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Templated
      template:
        src: content/web-content.j2
        dest: /var/www/html/index.html
      notify: Restarted nginx

  handlers:
    - name: Restarted nginx
      service:
        name: nginx
        state: restarted